name: agatha

services:

  redis:
    container_name: redis
    image: gperdrizet/agatha:redis
    restart: unless-stopped
    environment:
      REDIS_IP: $REDIS_IP
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - $REDIS_PORT:$REDIS_PORT
    privileged: true

  agatha_api:
    container_name: agatha_api
    image: gperdrizet/agatha:api
    restart: unless-stopped
    environment:
      HOST_IP: $HOST_IP
      FLASK_PORT: $FLASK_PORT
      REDIS_IP: $REDIS_IP
      REDIS_PORT: $REDIS_PORT
      HF_TOKEN: $HF_TOKEN
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - $FLASK_PORT:$FLASK_PORT
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1', '2']
            capabilities: [gpu]

  agatha_bot:
    container_name:  agatha_bot
    image: gperdrizet/agatha:bot
    restart: unless-stopped
    environment:
      HOST_IP: agatha_api
      FLASK_PORT: $FLASK_PORT
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN