name: agatha

services:

  redis:
    container_name: redis
    image: gperdrizet/agatha:redis-local
    restart: unless-stopped
    environment:
      REDIS_IP: '0.0.0.0'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - '6379:6379'
    command: ./start_server.sh
    privileged: true

  api:
    container_name: api
    image: gperdrizet/agatha:api-local
    restart: unless-stopped
    environment:
      HOST_IP: '0.0.0.0'
      FLASK_PORT: '5000'
      REDIS_IP: redis
      REDIS_PORT: '6379'
      HF_TOKEN: $HF_TOKEN
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1', '2']
            capabilities: [gpu]
    command: ./start_api.sh

  bot:
    container_name: bot
    image: gperdrizet/agatha:bot-local
    restart: unless-stopped
    environment:
      HOST_IP: api
      FLASK_PORT: '5000'
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN
    command: python3 ./bot.py